updated yml

diff --git a/.azdo/pipelines/templates/continuous-deployment.yml b/.azdo/pipelines/templates/continuous-deployment.yml
--- a/.azdo/pipelines/templates/continuous-deployment.yml
+++ b/.azdo/pipelines/templates/continuous-deployment.yml
@@ -245,7 +245,7 @@ jobs:
             parameters:
               AzureSubscription: ${{ variables.AzureSubscription }}
               AppName: efs-orchestrator
-              MaxWaitTime: 1
+              MaxWaitTime: 15
 
           - ${{ if eq(parameters.IncludeAddsMock, true) }}:
 
@@ -255,44 +255,57 @@ jobs:
                 AppName: adds-mocks-efs
                 MaxWaitTime: 1
 
-          - template: check-container.yml
-            parameters:
-              AzureSubscription: ${{ variables.AzureSubscription }}
-              AppName: efs-redis
-              MaxWaitTime: 1
+          # - template: check-container.yml
+          #   parameters:
+          #     AzureSubscription: ${{ variables.AzureSubscription }}
+          #     AppName: efs-redis
+          #     MaxWaitTime: 1
 
-        - task: AzureCLI@2
-          displayName: 'Set Orchestrator Endpoint Variable'
-          condition: always()
-          inputs:
-            workingDirectory: $(Build.SourcesDirectory)/efs/src/UKHO.ADDS.EFS.LocalHost
-            azureSubscription: ${{ variables.AzureSubscription }}
-            scriptType: bash
-            scriptLocation: inlineScript
-            inlineScript: |
-              # ENV_NAME="${AZURE_ENV_NAME}"
-              # RESOURCE_GROUP="efs-$ENV_NAME-rg"
-              # FQDN=$(az containerapp show \
-              #   --name efs-orchestrator \
-              #   --resource-group "$RESOURCE_GROUP" \
-              #   --query properties.configuration.ingress.fqdn -o tsv)
-              # if [ -z "$FQDN" ]; then
-              #   echo "##vso[task.logissue type=error]Could not retrieve FQDN for efs-orchestrator"
-              #   exit 1
-              # fi
-              # URL="https://$FQDN"
-              # echo "Orchestrator Endpoint: $URL"
-              # echo "##vso[task.setvariable variable=ORCHESTRATOR_URL]$URL"
-              DOMAIN=$(azd env get-value EFS_CAE_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN)
-              URL="https://efs-orchestrator.$DOMAIN"
-              echo "Orchestrator Endpoint: $URL"
-              echo "##vso[task.setvariable variable=ORCHESTRATOR_URL]$URL"
+          - task: PowerShell@2
+            displayName: 'Set Orchestrator Endpoint Variable'
+            inputs:
+              targetType: 'inline'
+              workingDirectory: $(Build.SourcesDirectory)/efs/src/UKHO.ADDS.EFS.LocalHost
+              script: |
+                $domain = & azd env get-value EFS_CAE_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN
+                $url = "https://efs-orchestrator.$domain"
+                Write-Host "Orchestrator Endpoint: $url"
+                Write-Host "##vso[task.setvariable variable=ORCHESTRATOR_URL]$url"
 
-        - task: PowerShell@2
-          displayName: "healthcheck_validation"
-          condition: always()
-          inputs:
-            targetType: filePath
-            filePath: "$(Build.SourcesDirectory)/efs/.azdo/pipelines/powershell/CheckServiceStatus.ps1"
-            arguments: "-healthEndPointUrl $(ORCHESTRATOR_URL)/health -waitTimeInMinute 2 -onErrorContinue 0"
+          - task: PowerShell@2
+            displayName: "healthcheck_validation"
+            condition: always()
+            inputs:
+              targetType: filePath
+              filePath: "$(Build.SourcesDirectory)/efs/.azdo/pipelines/powershell/CheckServiceStatus.ps1"
+              arguments: "-healthEndPointUrl $(ORCHESTRATOR_URL)/health -waitTimeInMinute 2 -onErrorContinue 0"
+
+        # - task: AzureCLI@2
+        #   displayName: 'Set Orchestrator Endpoint Variable'
+        #   condition: always()
+        #   inputs:
+        #     workingDirectory: $(Build.SourcesDirectory)/efs/src/UKHO.ADDS.EFS.LocalHost
+        #     azureSubscription: ${{ variables.AzureSubscription }}
+        #     scriptType: bash
+        #     scriptLocation: inlineScript
+        #     inlineScript: |
+        #       # ENV_NAME="${AZURE_ENV_NAME}"
+        #       # RESOURCE_GROUP="efs-$ENV_NAME-rg"
+        #       # FQDN=$(az containerapp show \
+        #       #   --name efs-orchestrator \
+        #       #   --resource-group "$RESOURCE_GROUP" \
+        #       #   --query properties.configuration.ingress.fqdn -o tsv)
+        #       # if [ -z "$FQDN" ]; then
+        #       #   echo "##vso[task.logissue type=error]Could not retrieve FQDN for efs-orchestrator"
+        #       #   exit 1
+        #       # fi
+        #       # URL="https://$FQDN"
+        #       # echo "Orchestrator Endpoint: $URL"
+        #       # echo "##vso[task.setvariable variable=ORCHESTRATOR_URL]$URL"
+        #       DOMAIN=$(azd env get-value EFS_CAE_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN)
+        #       URL="https://efs-orchestrator.$DOMAIN"
+        #       echo "Orchestrator Endpoint: $URL"
+        #       echo "##vso[task.setvariable variable=ORCHESTRATOR_URL]$URL"
+
+
 
