yml changes

diff --git a/.azdo/pipelines/templates/continuous-deployment.yml b/.azdo/pipelines/templates/continuous-deployment.yml
--- a/.azdo/pipelines/templates/continuous-deployment.yml
+++ b/.azdo/pipelines/templates/continuous-deployment.yml
@@ -284,36 +284,26 @@ jobs:
               AdditionalDebugging: ${{ parameters.AdditionalDebugging }}
               DeployApp: ${{ parameters.DeployBuilderS100 }}
 
-          - task: PowerShell@2
+          - task: AzureCLI@2
             displayName: 'Set Orchestrator Endpoint Variable'
             inputs:
-              targetType: 'inline'
-              pwsh: true
-              script: |
-                # Get container app FQDN first using Azure CLI
-                $resourceGroup = "efs-$env:AZURE_ENV_NAME-rg"
-                $containerAppName = "efs-orchestrator"
-                
-                Write-Host "Getting container app FQDN from resource group: $resourceGroup"
-                
-                try {
-                    $fqdn = az containerapp show `
-                        --name $containerAppName `
-                        --resource-group $resourceGroup `
-                        --query "properties.configuration.ingress.fqdn" -o tsv
-                    
-                    if (-not $fqdn) {
-                        throw "Could not retrieve FQDN from container app"
-                    }
-                    
-                    $url = "https://$fqdn"
-                    Write-Host "Orchestrator URL: $url"
-                    Write-Host "##vso[task.setvariable variable=ORCHESTRATOR_URL]$url"
-                }
-                catch {
-                    Write-Error "Failed to get container app FQDN: $_"
-                    throw
-                }
+              azureSubscription: ${{ variables.AzureSubscription }}
+              scriptType: bash
+              scriptLocation: inlineScript
+              inlineScript: |
+                ENV_NAME="${AZURE_ENV_NAME}"
+                RESOURCE_GROUP="efs-$ENV_NAME-rg"
+                FQDN=$(az containerapp show \
+                  --name efs-orchestrator \
+                  --resource-group "$RESOURCE_GROUP" \
+                  --query properties.configuration.ingress.fqdn -o tsv)
+                if [ -z "$FQDN" ]; then
+                  echo "##vso[task.logissue type=error]Could not retrieve FQDN for efs-orchestrator"
+                  exit 1
+                fi
+                URL="https://$FQDN"
+                echo "Orchestrator Endpoint: $URL"
+                echo "##vso[task.setvariable variable=ORCHESTRATOR_URL]$URL"
 
           - template: healthcheck_validation.yml
             parameters:
