Updated the Builder dockerfile to correctly install and run Tomcat, with supporting code changes. (#33)

diff --git a/src/UKHO.ADDS.EFS.Builder.S100/Dockerfile b/src/UKHO.ADDS.EFS.Builder.S100/Dockerfile
--- a/src/UKHO.ADDS.EFS.Builder.S100/Dockerfile
+++ b/src/UKHO.ADDS.EFS.Builder.S100/Dockerfile
@@ -1,25 +1,187 @@
-﻿# Visual Studio does not like Dockerfiles that have multiple stages - it only recognises the first stage. So, we have to use a single stage Dockerfile.
-# Also note that this dockerfile must be in the same directory as the .csproj file, otherwise Visual Studio will not recognise it as a debug target.
+﻿#
+# This dockerfile builds the EFS S100 Builder container. It is based on the Eclipse Temurin JDK 8 base (Ubuntu)
+#
+# It downloads and builds the Tomcat source, configures Tomcat and installs the IIC WAR application. It then
+# downloads and installs the .NET 9 SDK, builds the S100 Builder application and sets this as the ENTRYPOINT
+# for the container. 
+#
 
-FROM mcr.microsoft.com/dotnet/sdk:9.0
+FROM eclipse-temurin:8-jdk-noble
+
+ENV CATALINA_HOME /usr/local/tomcat
+ENV PATH $CATALINA_HOME/bin:$PATH
+
+# CHANGE
+ENV PATH /app/build:$PATH
+
+RUN mkdir -p "$CATALINA_HOME"
+
+WORKDIR $CATALINA_HOME
+
+# let "Tomcat Native" live somewhere isolated
+ENV TOMCAT_NATIVE_LIBDIR $CATALINA_HOME/native-jni-lib
+ENV LD_LIBRARY_PATH ${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$TOMCAT_NATIVE_LIBDIR
+
+ENV TOMCAT_MAJOR 9
+ENV TOMCAT_VERSION 9.0.100
+ENV TOMCAT_SHA512 e0b1379866d09b54f2743afb382c32a33bca9652c379467c1fa0a5b15a1b98830ae23fb1d8f96c43148844ce95b6c1d22a66db3f8efaf41f225b158c3cb71c92
+
+RUN set -eux; \
+	\
+	savedAptMark="$(apt-mark showmanual)"; \
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
+		ca-certificates \
+		curl \
+		gnupg \
+	; \
+	\
+	ddist() { \
+		local f="$1"; shift; \
+		local distFile="$1"; shift; \
+		local mvnFile="${1:-}"; \
+		local success=; \
+		local distUrl=; \
+		for distUrl in \
+# https://apache.org/history/mirror-history.html
+			"https://dlcdn.apache.org/$distFile" \
+# if the version is outdated, we have to pull from the archive
+			"https://archive.apache.org/dist/$distFile" \
+# if all else fails, let's try Maven (https://www.mail-archive.com/users@tomcat.apache.org/msg134940.html; https://mvnrepository.com/artifact/org.apache.tomcat/tomcat; https://repo1.maven.org/maven2/org/apache/tomcat/tomcat/)
+			${mvnFile:+"https://repo1.maven.org/maven2/org/apache/tomcat/tomcat/$mvnFile"} \
+		; do \
+			if curl -fL -o "$f" "$distUrl" && [ -s "$f" ]; then \
+				success=1; \
+				break; \
+			fi; \
+		done; \
+		[ -n "$success" ]; \
+	}; \
+	\
+	ddist 'tomcat.tar.gz' "tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz" "$TOMCAT_VERSION/tomcat-$TOMCAT_VERSION.tar.gz"; \
+	echo "$TOMCAT_SHA512 *tomcat.tar.gz" | sha512sum --strict --check -; \
+	ddist 'tomcat.tar.gz.asc' "tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz.asc" "$TOMCAT_VERSION/tomcat-$TOMCAT_VERSION.tar.gz.asc"; \
+	GNUPGHOME="$(mktemp -d)"; export GNUPGHOME; \
+	curl -fL -o upstream-KEYS 'https://www.apache.org/dist/tomcat/tomcat-9/KEYS'; \
+	gpg --batch --import upstream-KEYS; \
+# filter upstream KEYS file to *just* known/precomputed fingerprints
+	printf '' > filtered-KEYS; \
+# see https://www.apache.org/dist/tomcat/tomcat-9/KEYS
+	for key in \
+		'DCFD35E0BF8CA7344752DE8B6FB21E8933C60243' \
+		'A9C5DF4D22E99998D9875A5110C01C5A2F6059E7' \
+		'48F8E69F6390C9F25CFEDCD268248959359E722B' \
+	; do \
+		gpg --batch --fingerprint "$key"; \
+		gpg --batch --export --armor "$key" >> filtered-KEYS; \
+	done; \
+	gpgconf --kill all; \
+	rm -rf "$GNUPGHOME"; \
+	GNUPGHOME="$(mktemp -d)"; export GNUPGHOME; \
+	gpg --batch --import filtered-KEYS; \
+	gpg --batch --verify tomcat.tar.gz.asc tomcat.tar.gz; \
+	tar -xf tomcat.tar.gz --strip-components=1; \
+	rm bin/*.bat; \
+	rm tomcat.tar.gz*; \
+	gpgconf --kill all; \
+	rm -rf "$GNUPGHOME"; \
+	\
+# https://tomcat.apache.org/tomcat-9.0-doc/security-howto.html#Default_web_applications
+	mv webapps webapps.dist; \
+	mkdir webapps; \
+# we don't delete them completely because they're frankly a pain to get back for users who do want them, and they're generally tiny (~7MB)
+	\
+	nativeBuildDir="$(mktemp -d)"; \
+	tar -xf bin/tomcat-native.tar.gz -C "$nativeBuildDir" --strip-components=1; \
+	apt-get install -y --no-install-recommends \
+		dpkg-dev \
+		gcc \
+		libapr1-dev \
+		libssl-dev \
+		make \
+	; \
+	( \
+		export CATALINA_HOME="$PWD"; \
+		cd "$nativeBuildDir/native"; \
+		gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; \
+		aprConfig="$(command -v apr-1-config)"; \
+		./configure \
+			--build="$gnuArch" \
+			--libdir="$TOMCAT_NATIVE_LIBDIR" \
+			--prefix="$CATALINA_HOME" \
+			--with-apr="$aprConfig" \
+			--with-java-home="$JAVA_HOME" \
+			--with-ssl \
+		; \
+		nproc="$(nproc)"; \
+		make -j "$nproc"; \
+		make install; \
+	); \
+	rm -rf "$nativeBuildDir"; \
+	rm bin/tomcat-native.tar.gz; \
+	\
+# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
+	apt-mark auto '.*' > /dev/null; \
+	[ -z "$savedAptMark" ] || apt-mark manual $savedAptMark > /dev/null; \
+	find "$TOMCAT_NATIVE_LIBDIR" -type f -executable -exec ldd '{}' ';' \
+		| awk '/=>/ { print $(NF-1) }' \
+		| xargs -rt readlink -e \
+		| sort -u \
+		| xargs -rt dpkg-query --search \
+		| cut -d: -f1 \
+		| sort -u \
+		| tee "$TOMCAT_NATIVE_LIBDIR/.dependencies.txt" \
+		| xargs -r apt-mark manual \
+	; \
+	\
+	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+	rm -rf /var/lib/apt/lists/*; \
+	\
+# sh removes env vars it doesn't support (ones with periods)
+# https://github.com/docker-library/tomcat/issues/77
+	find ./bin/ -name '*.sh' -exec sed -ri 's|^#!/bin/sh$|#!/usr/bin/env bash|' '{}' +; \
+	\
+# fix permissions (especially for running as non-root)
+# https://github.com/docker-library/tomcat/issues/35
+	chmod -R +rX .; \
+	chmod 1777 logs temp work; \
+	\
+# smoke test
+	catalina.sh version
+
+# verify Tomcat Native is working properly
+RUN set -eux; \
+	nativeLines="$(catalina.sh configtest 2>&1)"; \
+	nativeLines="$(echo "$nativeLines" | grep 'Apache Tomcat Native')"; \
+	nativeLines="$(echo "$nativeLines" | sort -u)"; \
+	if ! echo "$nativeLines" | grep -E 'INFO: Loaded( APR based)? Apache Tomcat Native library' >&2; then \
+		echo >&2 "$nativeLines"; \
+		exit 1; \
+	fi
+
+# copy in war file to webapps for unpacking...
+COPY UKHO.ADDS.EFS.Builder.S100/xchg-2.7.war /usr/local/tomcat/webapps/
+ADD UKHO.ADDS.EFS.Builder.S100/root2.tar.gz /usr/local/tomcat/
+
+# UKHO additions
+# Install .net, build the S100 builder
+
+RUN apt-get update && \
+    apt-get install -y \
+    wget \
+    apt-transport-https \
+    software-properties-common 
+
+RUN wget -q https://packages.microsoft.com/keys/microsoft.asc -O /etc/apt/trusted.gpg.d/microsoft.asc
+
+RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/prod.list -O /etc/apt/sources.list.d/dotnetdev.list
+
+RUN apt-get update && \
+    apt-get install -y dotnet-sdk-9.0
 
 ARG BUILD_CONFIGURATION=Debug
-ARG CACHEBUSTER=1
 
-ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
-ENV CATALINA_HOME=/usr/local/tomcat
-ENV PATH="$JAVA_HOME/bin:$CATALINA_HOME/bin:$PATH"
-
-# Install OpenJDK, wget, and Tomcat
-RUN apt-get update && apt-get install -y openjdk-17-jdk wget && \
-    wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.102/bin/apache-tomcat-9.0.102.tar.gz && \
-    tar -xzvf apache-tomcat-9.0.102.tar.gz && \
-    mv apache-tomcat-9.0.102 /usr/local/tomcat && \
-    rm -rf /var/lib/apt/lists/*
-
-RUN echo "Tomcat installed in /usr/local/tomcat" && ls /usr/local/tomcat
-
-WORKDIR /src
+WORKDIR /dotnet
 
 # Copy and restore projects
 COPY ["Directory.Build.props", "."]
@@ -29,19 +191,12 @@ RUN dotnet restore UKHO.ADDS.EFS.Builder.S100/UKHO.ADDS.EFS.Builder.S100.csproj
 
 # Copy remaining files and build
 COPY . .
-WORKDIR /src/UKHO.ADDS.EFS.Builder.S100
-RUN dotnet build UKHO.ADDS.EFS.Builder.S100.csproj -c $BUILD_CONFIGURATION -o /app/build
+WORKDIR /dotnet/UKHO.ADDS.EFS.Builder.S100
+RUN dotnet build UKHO.ADDS.EFS.Builder.S100.csproj -c $BUILD_CONFIGURATION -o /app
 
-# Copy WAR to Tomcat
-COPY UKHO.ADDS.EFS.Builder.S100/Tomcat/xchg-2.7.war /usr/local/tomcat/webapps/
+# It is critical that the container WORKDIR is set to CATALINA_HOME here, or Tomcat will not start properly
+WORKDIR $CATALINA_HOME
 
-# No need to copy anything — the build output is already there
-WORKDIR /app/build
-
-# The .NET process orchestrates Tomcat, so just start that. Visual Studio also hijacks the ENTRYPOINT and injects its own
-# stuff as PID 1, so any bash shells don't run properly when debugging from Visual Studio...
-ENTRYPOINT ["dotnet", "/app/build/UKHO.ADDS.EFS.Builder.S100.dll"]
+ENTRYPOINT ["dotnet", "/app/UKHO.ADDS.EFS.Builder.S100.dll"]
 
 EXPOSE 8080 5000
-
-
